name: VehicleDiagnosisELMHost
options:
  minimumXcodeGenVersion: 2.38.0
  xcodeVersion: "15.4"
  projectFormat: xcode15_0
  deploymentTarget:
    iOS: "16.0"
settings:
  base:
    SWIFT_VERSION: "5.9"
    PRODUCT_BUNDLE_IDENTIFIER: com.mukiguri.VehicleDiagnosisELMHost
targets:
  VehicleDiagnosisELMHost:
    type: application
    platform: iOS
    sources:
      - Sources
    settings:
      base:
        INFOPLIST_FILE: Sources/Info.plist
    dependencies:
      - package: ELM327BLEConnector
        product: ELM327BLEConnector
  VehicleDiagnosisELMHostTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - Tests
    dependencies:
      - target: VehicleDiagnosisELMHost
      - package: ELM327BLEConnector
        product: ELM327BLEConnector
  ELM327BLEConnectorTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: ../ELM327BLEConnector/Tests/ELM327BLEConnectorTests
    dependencies:
      - package: ELM327BLEConnector
        product: ELM327BLEConnector
packages:
  ELM327BLEConnector:
    path: ../ELM327BLEConnector
